#!/usr/bin/node
// Send command to set the configuration of a light.

const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);
var screenLogic_password = process.env.ScreenLogic_password;

connect(new ScreenLogic.UnitConnection(80, myArgs[0], screenLogic_password), parseInt(myArgs[1]));

function connect(client, command) {
    client.on('loggedIn', function() {
      this.sendLightCommand(0, command);
      client.close();
    });
    client.connect();
  }