#!/usr/bin/node
// Send command to set the state of a circuit.
 
const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);
var screenLogic_ip = process.env.SCREENLOGICIP;

connect(new ScreenLogic.UnitConnection(80, screenLogic_ip), parseInt(myArgs[0]), parseInt(myArgs[1]));

function connect(client, poolOrSpa, level) {
  client.on('loggedIn', function() {
    this.getSaltCellConfig();
  }).on('saltCellConfig', function(saltCellConfig) {
    if(poolOrSpa == 0)
      this.setSaltCellOutput(0, level, saltCellConfig.level2);
    else
      this.setSaltCellOutput(0, saltCellConfig.level1, level);
    client.close();
  });

  client.connect();
}

