#!/usr/bin/node
// Send command to set the state of a circuit.
 
const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);

connect(new ScreenLogic.UnitConnection(80, myArgs[0]), parseInt(myArgs[1]), parseInt(myArgs[2]));

function connect(client, circuit, onoff) {
  client.on('loggedIn', function() {
    this.setCircuitState(0, circuit, onoff);
    client.close();
  });

  client.connect();
}

