#!/usr/bin/node
// Send command to set the configuration of a light.

const ScreenLogic = require('./index');

var myArgs = process.argv.slice(2);
var screenLogic_ip = process.env.SCREENLOGICIP;

connect(new ScreenLogic.UnitConnection(80, screenLogic_ip), parseInt(myArgs[0]));

function connect(client, command) {
    client.on('loggedIn', function() {
      this.sendLightCommand(0, command);
      client.close();
    });
    client.connect();
  }