#!/usr/bin/node
const ScreenLogic = require('./index');

var finder = new ScreenLogic.FindUnits();
finder.on('serverFound', function(server) {
  finder.close();
  connect(new ScreenLogic.UnitConnection(server));
});

finder.search();

function connect(client) {
  client.on('loggedIn', function() {
    this.setCircuitState(0, 500, 1);
    client.close();
  });

  client.connect();
}

